<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Add the js library.
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function webauthn_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if($form['#id'] == 'WebAuthnSetup') {
    $form['#attached']['library'][] = 'webauthn/webauthn_setup';
  }

  if($form['#id'] == 'WebAuthnValidation') {
    $form['#attached']['library'][] = 'webauthn/webauthn_validation';
  }
}
